"""add checklist_scores table

Revision ID: 926e9b54c276
Revises: c80124acff98
Create Date: 2026-09-11 15:48:36.036545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926e9b54c276'
down_revision: Union[str, None] = 'c80124acff98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sample_size_ok', sa.Boolean(), nullable=True),
    sa.Column('btts_rate_ok', sa.Boolean(), nullable=True),
    sa.Column('clean_sheet_rate_ok', sa.Boolean(), nullable=True),
    sa.Column('combined_goals_ok', sa.Boolean(), nullable=True),
    sa.Column('league_gap_ok', sa.Boolean(), nullable=True),
    sa.Column('shots_on_target_ok', sa.Boolean(), nullable=True),
    sa.Column('attack_defence_split_ok', sa.Boolean(), nullable=True),
    sa.Column('xg_ok', sa.Boolean(), nullable=True),
    sa.Column('h2h_ok', sa.Boolean(), nullable=True),
    sa.Column('recent_form_ok', sa.Boolean(), nullable=True),
    sa.Column('vs_league_avg_ok', sa.Boolean(), nullable=True),
    sa.Column('early_goals_ok', sa.Boolean(), nullable=True),
    sa.Column('late_goals_ok', sa.Boolean(), nullable=True),
    sa.Column('checks_passed', sa.Integer(), nullable=False),
    sa.Column('checks_computable', sa.Integer(), nullable=False),
    sa.Column('score_pct', sa.Float(), nullable=True),
    sa.Column('key_players_missing', sa.Text(), nullable=False),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('data_gaps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('checks_computable >= 0 AND checks_computable <= 13', name='ck_checklist_scores_computable_range'),
    sa.CheckConstraint('checks_passed <= checks_computable', name='ck_checklist_scores_passed_le_computable'),
    sa.CheckConstraint('checks_passed >= 0 AND checks_passed <= 13', name='ck_checklist_scores_passed_range'),
    sa.CheckConstraint('score_pct IS NULL OR (score_pct >= 0 AND score_pct <= 1)', name='ck_checklist_scores_score_pct_range'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', name='uq_checklist_scores_fixture')
    )
    op.create_index('ix_checklist_scores_computed_at', 'checklist_scores', ['computed_at'], unique=False)
    op.create_index('ix_checklist_scores_score_pct', 'checklist_scores', ['score_pct'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checklist_scores_score_pct', table_name='checklist_scores')
    op.drop_index('ix_checklist_scores_computed_at', table_name='checklist_scores')
    op.drop_table('checklist_scores')
    # ### end Alembic commands ###
