"""initial schema

Revision ID: c80124acff98
Revises: 
Create Date: 2026-09-08 15:39:52.635876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c80124acff98'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.String(length=64), nullable=False),
    sa.Column('train_start_date', sa.Date(), nullable=False),
    sa.Column('train_end_date', sa.Date(), nullable=False),
    sa.Column('test_start_date', sa.Date(), nullable=False),
    sa.Column('test_end_date', sa.Date(), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('segment_type', sa.String(length=32), nullable=False),
    sa.Column('segment_value', sa.String(length=64), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('roc_auc', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_score', sa.Float(), nullable=True),
    sa.Column('recall_score', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('predicted_probability_mean', sa.Float(), nullable=True),
    sa.Column('actual_frequency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("model_type IN ('poisson', 'ml', 'sportmonks', 'raw_ensemble', 'final')", name='ck_backtest_results_model_type_valid'),
    sa.CheckConstraint("segment_type IN ('overall', 'league', 'season', 'probability_band', 'home_away')", name='ck_backtest_results_segment_type_valid'),
    sa.CheckConstraint('sample_size >= 0', name='ck_backtest_results_sample_size_nonneg'),
    sa.CheckConstraint('test_start_date >= train_end_date', name='ck_backtest_results_no_time_overlap'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_run_id', 'model_type', 'segment_type', 'segment_value', name='uq_backtest_results_run_model_segment')
    )
    op.create_index('ix_backtest_results_model_segment', 'backtest_results', ['model_type', 'segment_type'], unique=False)
    op.create_index('ix_backtest_results_run_id', 'backtest_results', ['backtest_run_id'], unique=False)
    op.create_index('ix_backtest_results_test_window', 'backtest_results', ['test_start_date', 'test_end_date'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leagues_country_id', 'leagues', ['country_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=16), nullable=True),
    sa.Column('country_id', sa.BigInteger(), nullable=True),
    sa.Column('country_name', sa.String(length=255), nullable=True),
    sa.Column('founded', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_country_id', 'teams', ['country_id'], unique=False)
    op.create_table('league_model_performance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('evaluation_window_start', sa.Date(), nullable=False),
    sa.Column('evaluation_window_end', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('league_reliability_score', sa.Float(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("model_type IN ('poisson', 'ml', 'sportmonks', 'raw_ensemble', 'final')", name='ck_league_model_performance_model_type_valid'),
    sa.CheckConstraint('league_reliability_score >= 0 AND league_reliability_score <= 1', name='ck_league_model_performance_reliability_range'),
    sa.CheckConstraint('sample_size >= 0', name='ck_league_model_performance_sample_size_nonneg'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'model_type', 'evaluation_window_end', name='uq_league_model_performance_league_window')
    )
    op.create_index('ix_league_model_performance_is_eligible', 'league_model_performance', ['is_eligible'], unique=False)
    op.create_index('ix_league_model_performance_league_id', 'league_model_performance', ['league_id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seasons_league_id', 'seasons', ['league_id'], unique=False)
    op.create_table('fixtures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('league_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('kickoff', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('total_goals', sa.Integer(), sa.Computed('home_goals + away_goals', persisted=True), nullable=True),
    sa.Column('over_2_5', sa.Boolean(), sa.Computed('CASE WHEN home_goals IS NULL OR away_goals IS NULL THEN NULL ELSE (home_goals + away_goals) >= 3 END', persisted=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('NS', 'LIVE', 'HT', 'FT', 'AET', 'PEN', 'POSTP', 'CANC', 'ABAN', 'SUSP', 'TBD')", name='ck_fixtures_status_valid'),
    sa.CheckConstraint('away_goals IS NULL OR away_goals >= 0', name='ck_fixtures_away_goals_nonneg'),
    sa.CheckConstraint('home_goals IS NULL OR home_goals >= 0', name='ck_fixtures_home_goals_nonneg'),
    sa.CheckConstraint('home_team_id <> away_team_id', name='ck_fixtures_distinct_teams'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fixtures_away_team', 'fixtures', ['away_team_id'], unique=False)
    op.create_index('ix_fixtures_home_team', 'fixtures', ['home_team_id'], unique=False)
    op.create_index('ix_fixtures_kickoff', 'fixtures', ['kickoff'], unique=False)
    op.create_index('ix_fixtures_league_season', 'fixtures', ['league_id', 'season_id'], unique=False)
    op.create_index('ix_fixtures_status', 'fixtures', ['status'], unique=False)
    op.create_table('match_features',
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('league_avg_goals', sa.Float(), nullable=True),
    sa.Column('league_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('league_home_goals_avg', sa.Float(), nullable=True),
    sa.Column('league_away_goals_avg', sa.Float(), nullable=True),
    sa.Column('league_sample_size', sa.Integer(), nullable=True),
    sa.Column('h2h_matches_played', sa.Integer(), nullable=True),
    sa.Column('h2h_avg_total_goals', sa.Float(), nullable=True),
    sa.Column('h2h_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('h2h_btts_pct', sa.Float(), nullable=True),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_completeness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fixture_id')
    )
    op.create_index('ix_match_features_computed_at', 'match_features', ['computed_at'], unique=False)
    op.create_table('match_statistics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('corners', sa.Integer(), nullable=True),
    sa.Column('big_chances_created', sa.Integer(), nullable=True),
    sa.Column('possession_percentage', sa.Float(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('possession_percentage IS NULL OR (possession_percentage >= 0 AND possession_percentage <= 100)', name='ck_match_statistics_possession_range'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_id', name='uq_match_statistics_fixture_team')
    )
    op.create_index('ix_match_statistics_team_id', 'match_statistics', ['team_id'], unique=False)
    op.create_table('match_xg',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('xg IS NULL OR xg >= 0', name='ck_match_xg_nonneg'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'team_id', name='uq_match_xg_fixture_team')
    )
    op.create_index('ix_match_xg_team_id', 'match_xg', ['team_id'], unique=False)
    op.create_table('odds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('bookmaker', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('over_odds', sa.Float(), nullable=True),
    sa.Column('under_odds', sa.Float(), nullable=True),
    sa.Column('over_implied_probability', sa.Float(), sa.Computed('CASE WHEN over_odds > 0 THEN 1.0 / over_odds ELSE NULL END', persisted=True), nullable=True),
    sa.Column('under_implied_probability', sa.Float(), sa.Computed('CASE WHEN under_odds > 0 THEN 1.0 / under_odds ELSE NULL END', persisted=True), nullable=True),
    sa.Column('overround', sa.Float(), sa.Computed('CASE WHEN over_odds > 0 AND under_odds > 0 THEN (1.0 / over_odds) + (1.0 / under_odds) ELSE NULL END', persisted=True), nullable=True),
    sa.Column('market_probability', sa.Float(), sa.Computed('CASE WHEN over_odds > 0 AND under_odds > 0 THEN (1.0 / over_odds) / ((1.0 / over_odds) + (1.0 / under_odds)) ELSE NULL END', persisted=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('over_odds IS NULL OR over_odds > 1', name='ck_odds_over_odds_valid'),
    sa.CheckConstraint('under_odds IS NULL OR under_odds > 1', name='ck_odds_under_odds_valid'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'bookmaker', 'market', 'retrieved_at', name='uq_odds_fixture_bookmaker_market_snapshot')
    )
    op.create_index('ix_odds_fixture_id', 'odds', ['fixture_id'], unique=False)
    op.create_index('ix_odds_retrieved_at', 'odds', ['retrieved_at'], unique=False)
    op.create_table('sportmonks_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('over_2_5_probability', sa.Float(), nullable=True),
    sa.Column('btts_probability', sa.Float(), nullable=True),
    sa.Column('predicted_home_goals', sa.Float(), nullable=True),
    sa.Column('predicted_away_goals', sa.Float(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('btts_probability IS NULL OR (btts_probability >= 0 AND btts_probability <= 1)', name='ck_sportmonks_predictions_btts_range'),
    sa.CheckConstraint('over_2_5_probability IS NULL OR (over_2_5_probability >= 0 AND over_2_5_probability <= 1)', name='ck_sportmonks_predictions_over_2_5_range'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id')
    )
    op.create_index('ix_sportmonks_predictions_retrieved_at', 'sportmonks_predictions', ['retrieved_at'], unique=False)
    op.create_table('team_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_last3_matches_played', sa.Integer(), nullable=True),
    sa.Column('overall_last3_goals_scored', sa.Float(), nullable=True),
    sa.Column('overall_last3_goals_conceded', sa.Float(), nullable=True),
    sa.Column('overall_last3_xg', sa.Float(), nullable=True),
    sa.Column('overall_last3_xga', sa.Float(), nullable=True),
    sa.Column('overall_last3_shots', sa.Float(), nullable=True),
    sa.Column('overall_last3_shots_on_target', sa.Float(), nullable=True),
    sa.Column('overall_last3_big_chances', sa.Float(), nullable=True),
    sa.Column('overall_last3_corners', sa.Float(), nullable=True),
    sa.Column('overall_last3_btts_pct', sa.Float(), nullable=True),
    sa.Column('overall_last3_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('overall_last5_matches_played', sa.Integer(), nullable=True),
    sa.Column('overall_last5_goals_scored', sa.Float(), nullable=True),
    sa.Column('overall_last5_goals_conceded', sa.Float(), nullable=True),
    sa.Column('overall_last5_xg', sa.Float(), nullable=True),
    sa.Column('overall_last5_xga', sa.Float(), nullable=True),
    sa.Column('overall_last5_shots', sa.Float(), nullable=True),
    sa.Column('overall_last5_shots_on_target', sa.Float(), nullable=True),
    sa.Column('overall_last5_big_chances', sa.Float(), nullable=True),
    sa.Column('overall_last5_corners', sa.Float(), nullable=True),
    sa.Column('overall_last5_btts_pct', sa.Float(), nullable=True),
    sa.Column('overall_last5_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('overall_last10_matches_played', sa.Integer(), nullable=True),
    sa.Column('overall_last10_goals_scored', sa.Float(), nullable=True),
    sa.Column('overall_last10_goals_conceded', sa.Float(), nullable=True),
    sa.Column('overall_last10_xg', sa.Float(), nullable=True),
    sa.Column('overall_last10_xga', sa.Float(), nullable=True),
    sa.Column('overall_last10_shots', sa.Float(), nullable=True),
    sa.Column('overall_last10_shots_on_target', sa.Float(), nullable=True),
    sa.Column('overall_last10_big_chances', sa.Float(), nullable=True),
    sa.Column('overall_last10_corners', sa.Float(), nullable=True),
    sa.Column('overall_last10_btts_pct', sa.Float(), nullable=True),
    sa.Column('overall_last10_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('venue_last3_matches_played', sa.Integer(), nullable=True),
    sa.Column('venue_last3_goals_scored', sa.Float(), nullable=True),
    sa.Column('venue_last3_goals_conceded', sa.Float(), nullable=True),
    sa.Column('venue_last3_xg', sa.Float(), nullable=True),
    sa.Column('venue_last3_xga', sa.Float(), nullable=True),
    sa.Column('venue_last3_shots', sa.Float(), nullable=True),
    sa.Column('venue_last3_shots_on_target', sa.Float(), nullable=True),
    sa.Column('venue_last3_big_chances', sa.Float(), nullable=True),
    sa.Column('venue_last3_corners', sa.Float(), nullable=True),
    sa.Column('venue_last3_btts_pct', sa.Float(), nullable=True),
    sa.Column('venue_last3_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('venue_last5_matches_played', sa.Integer(), nullable=True),
    sa.Column('venue_last5_goals_scored', sa.Float(), nullable=True),
    sa.Column('venue_last5_goals_conceded', sa.Float(), nullable=True),
    sa.Column('venue_last5_xg', sa.Float(), nullable=True),
    sa.Column('venue_last5_xga', sa.Float(), nullable=True),
    sa.Column('venue_last5_shots', sa.Float(), nullable=True),
    sa.Column('venue_last5_shots_on_target', sa.Float(), nullable=True),
    sa.Column('venue_last5_big_chances', sa.Float(), nullable=True),
    sa.Column('venue_last5_corners', sa.Float(), nullable=True),
    sa.Column('venue_last5_btts_pct', sa.Float(), nullable=True),
    sa.Column('venue_last5_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('venue_last10_matches_played', sa.Integer(), nullable=True),
    sa.Column('venue_last10_goals_scored', sa.Float(), nullable=True),
    sa.Column('venue_last10_goals_conceded', sa.Float(), nullable=True),
    sa.Column('venue_last10_xg', sa.Float(), nullable=True),
    sa.Column('venue_last10_xga', sa.Float(), nullable=True),
    sa.Column('venue_last10_shots', sa.Float(), nullable=True),
    sa.Column('venue_last10_shots_on_target', sa.Float(), nullable=True),
    sa.Column('venue_last10_big_chances', sa.Float(), nullable=True),
    sa.Column('venue_last10_corners', sa.Float(), nullable=True),
    sa.Column('venue_last10_btts_pct', sa.Float(), nullable=True),
    sa.Column('venue_last10_over_2_5_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'fixture_id', name='uq_team_features_team_fixture')
    )
    op.create_index('ix_team_features_as_of', 'team_features', ['as_of'], unique=False)
    op.create_index('ix_team_features_fixture_id', 'team_features', ['fixture_id'], unique=False)
    op.create_index('ix_team_features_team_id', 'team_features', ['team_id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('expected_home_goals', sa.Float(), nullable=True),
    sa.Column('expected_away_goals', sa.Float(), nullable=True),
    sa.Column('poisson_probability', sa.Float(), nullable=True),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('sportmonks_probability', sa.Float(), nullable=True),
    sa.Column('raw_ensemble_probability', sa.Float(), nullable=True),
    sa.Column('ensemble_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calibration_method', sa.String(length=32), nullable=True),
    sa.Column('final_probability', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('odds_id', sa.BigInteger(), nullable=True),
    sa.Column('market_probability', sa.Float(), nullable=True),
    sa.Column('market_odds_over', sa.Float(), nullable=True),
    sa.Column('market_odds_under', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), sa.Computed('CASE WHEN final_probability IS NOT NULL AND market_probability IS NOT NULL THEN final_probability - market_probability ELSE NULL END', persisted=True), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("calibration_method IS NULL OR calibration_method IN ('platt', 'isotonic', 'none')", name='ck_model_predictions_calibration_method_valid'),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name='ck_model_predictions_confidence_range'),
    sa.CheckConstraint('final_probability IS NULL OR (final_probability >= 0 AND final_probability <= 1)', name='ck_model_predictions_final_range'),
    sa.CheckConstraint('ml_probability IS NULL OR (ml_probability >= 0 AND ml_probability <= 1)', name='ck_model_predictions_ml_range'),
    sa.CheckConstraint('poisson_probability IS NULL OR (poisson_probability >= 0 AND poisson_probability <= 1)', name='ck_model_predictions_poisson_range'),
    sa.CheckConstraint('raw_ensemble_probability IS NULL OR (raw_ensemble_probability >= 0 AND raw_ensemble_probability <= 1)', name='ck_model_predictions_raw_ensemble_range'),
    sa.CheckConstraint('sportmonks_probability IS NULL OR (sportmonks_probability >= 0 AND sportmonks_probability <= 1)', name='ck_model_predictions_sportmonks_range'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['odds_id'], ['odds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'model_version', name='uq_model_predictions_fixture_version')
    )
    op.create_index('ix_model_predictions_fixture_id', 'model_predictions', ['fixture_id'], unique=False)
    op.create_index('ix_model_predictions_predicted_at', 'model_predictions', ['predicted_at'], unique=False)
    op.create_table('daily_rankings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ranking_date', sa.Date(), nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('model_prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=False),
    sa.Column('final_probability', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('market_probability', sa.Float(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.Column('league_reliability_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_daily_rankings_confidence_range'),
    sa.CheckConstraint('final_probability >= 0 AND final_probability <= 1', name='ck_daily_rankings_final_probability_range'),
    sa.CheckConstraint('rank >= 1', name='ck_daily_rankings_rank_positive'),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_prediction_id'], ['model_predictions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ranking_date', 'fixture_id', name='uq_daily_rankings_date_fixture'),
    sa.UniqueConstraint('ranking_date', 'rank', name='uq_daily_rankings_date_rank')
    )
    op.create_index('ix_daily_rankings_fixture_id', 'daily_rankings', ['fixture_id'], unique=False)
    op.create_index('ix_daily_rankings_ranking_date', 'daily_rankings', ['ranking_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_rankings_ranking_date', table_name='daily_rankings')
    op.drop_index('ix_daily_rankings_fixture_id', table_name='daily_rankings')
    op.drop_table('daily_rankings')
    op.drop_index('ix_model_predictions_predicted_at', table_name='model_predictions')
    op.drop_index('ix_model_predictions_fixture_id', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('ix_team_features_team_id', table_name='team_features')
    op.drop_index('ix_team_features_fixture_id', table_name='team_features')
    op.drop_index('ix_team_features_as_of', table_name='team_features')
    op.drop_table('team_features')
    op.drop_index('ix_sportmonks_predictions_retrieved_at', table_name='sportmonks_predictions')
    op.drop_table('sportmonks_predictions')
    op.drop_index('ix_odds_retrieved_at', table_name='odds')
    op.drop_index('ix_odds_fixture_id', table_name='odds')
    op.drop_table('odds')
    op.drop_index('ix_match_xg_team_id', table_name='match_xg')
    op.drop_table('match_xg')
    op.drop_index('ix_match_statistics_team_id', table_name='match_statistics')
    op.drop_table('match_statistics')
    op.drop_index('ix_match_features_computed_at', table_name='match_features')
    op.drop_table('match_features')
    op.drop_index('ix_fixtures_status', table_name='fixtures')
    op.drop_index('ix_fixtures_league_season', table_name='fixtures')
    op.drop_index('ix_fixtures_kickoff', table_name='fixtures')
    op.drop_index('ix_fixtures_home_team', table_name='fixtures')
    op.drop_index('ix_fixtures_away_team', table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index('ix_seasons_league_id', table_name='seasons')
    op.drop_table('seasons')
    op.drop_index('ix_league_model_performance_league_id', table_name='league_model_performance')
    op.drop_index('ix_league_model_performance_is_eligible', table_name='league_model_performance')
    op.drop_table('league_model_performance')
    op.drop_index('ix_teams_country_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_leagues_country_id', table_name='leagues')
    op.drop_table('leagues')
    op.drop_index('ix_backtest_results_test_window', table_name='backtest_results')
    op.drop_index('ix_backtest_results_run_id', table_name='backtest_results')
    op.drop_index('ix_backtest_results_model_segment', table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
